Afin de lancer l'environnement virtuel il faut aller dans le dossier ML et ecrire la commande .\env\Scripts\activate

Verification de la connection au compte github ssh -T git@github.com 

Verification de l'état : git status
Ajout de fichiers: git add .
Commit : git commit -m "Test"
Push : git push origin main

### Definitions
Machine learning algorithms that learn from input/output pairs are called **supervised learning** algorithms because a “teacher” provides supervision to the algorithms in the form of the desired outputs for each example that they learn from.

**Unsupervised algorithms** are the other type of algorithm that we will cover in this
book. In unsupervised learning, only the input data is known, and no known output
data is given to the algorithm. While there are many successful applications of these
methods, they are usually harder to understand and evaluate

Each entity or row here is known as a **sample** (or data point) in machine learning,
while the columns—the properties that describe these entities—are called **features**.

In [2]:
import sys
print("Python version: {}".format(sys.version))
import pandas as pd
print("pandas version: {}".format(pd.__version__))
import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))
import numpy as np
print("NumPy version: {}".format(np.__version__))
import scipy as sp
print("SciPy version: {}".format(sp.__version__))
import IPython
print("IPython version: {}".format(IPython.__version__))
import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))


Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
pandas version: 2.1.3
matplotlib version: 3.8.2
NumPy version: 1.26.2
SciPy version: 1.11.4
IPython version: 8.13.2
scikit-learn version: 1.5.1


## Exemple IRIS Classification 

Let’s assume that a hobby botanist is interested in distinguishing the species of some
iris flowers that she has found. She has collected some measurements associated with
each iris: the length and width of the petals and the length and width of the sepals, all
measured in centimeters.

She also has the measurements of some irises that have been previously identified by
an expert botanist as belonging to the species setosa, versicolor, or virginica.
Our goal is to build a machine learning model that can learn from the measurements
of these irises whose species is known, so that we can predict the species for a new
iris.

Because we have measurements for which we know the correct species of iris, this is a
supervised learning problem. In this problem, we want to predict one of several
options (the species of iris). This is an example of a **classification problem**.

The possible outputs (different species of irises) are called **classes**

The desired output for a single data point (an iris) is the species of this flower. For a
particular data point, the species it belongs to is called its **label**.

In [3]:
## Loading of the data
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [9]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))
#print(iris_dataset['DESCR'][:193] + "\n...")

#The value of the key target_names is an array of strings, containing the species of flower that we want to predict
print("Target names: {}".format(iris_dataset['target_names']))

#The value of feature_names is a list of strings, giving the description of each feature
print("Feature names: \n{}".format(iris_dataset['feature_names']))


Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Target names: ['setosa' 'versicolor' 'virginica']
Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Type of data: <class 'numpy.ndarray'>
Shape of data: (150, 4)


In [12]:
# Input
print("Type of data: {}".format(type(iris_dataset['data'])))
print("Shape of data: {}".format(iris_dataset['data'].shape))
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))


Type of data: <class 'numpy.ndarray'>
Shape of data: (150, 4)
First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
# Output
print("Shape of target: {}".format(iris_dataset['target'].shape))
print("Target:\n{}".format(iris_dataset['target']))

P31